permalink: /:categories/:title
title: mengw.io
description: WMXPY's Automated Bug Factory
url: https://mengw.io
feed: /atom.xml
github_username:  WMXPY 
author_info: <a href="http://mengw.io/">WMXPY</a>
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
author:
  name: WMXPY
exclude:
  - CNAME
  - LICENSE
  - _notes
  - _storage
  - _progess
  - .github
  - .vscode
  - docs