permalink: /:categories/:title

title: mengw.io
url: http://mengw.io
feed: /atom.xml
github_username:  WMXPY
author_info: <a href="http://mengw.io/">WMXPY</a>
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
