permalink: /:categories/:title

title: mengw.io
url: http://mengw.io
feed: /atom.xml
github_username:  WMXPY
author_info: <a href="http://mengw.io/">WMXPY</a>
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false